{% set name = "quantiphyse" %}
{% set version = "0.9.9.post2" %}
{% set sha256 = "420eca96d86f48c0e8c67884fe1ea39feefb8ddda87d857e27830bb9641d404a" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  entry_points:
    - quantiphyse = quantiphyse.qpmain:main
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  build:
  host:
    - python
    - pip
  run:
    - cython
    - matplotlib-base
    - nibabel
    - numpy
    - pandas
    - pillow
    - pyobjc-framework-cocoa  # [osx]
    - pyqtgraph >=0.11.1
    - pyside2
    - python
    - pyyaml
    - requests
    - scikit-image
    - scikit-learn
    - scipy
    - setuptools
    - six

test:
  imports:
    - PySide2
    - quantiphyse
    - quantiphyse.data
    - quantiphyse.gui
    - quantiphyse.icons
    - quantiphyse.packages
    - quantiphyse.packages.core
    - quantiphyse.packages.core.analysis
    - quantiphyse.packages.core.batch_builder
    - quantiphyse.packages.core.clustering
    - quantiphyse.packages.core.compare
    - quantiphyse.packages.core.data
    - quantiphyse.packages.core.experimental
    - quantiphyse.packages.core.histogram
    - quantiphyse.packages.core.overview
    - quantiphyse.packages.core.pca
    - quantiphyse.packages.core.radialprofile
    - quantiphyse.packages.core.registration
    - quantiphyse.packages.core.roi_builder
    - quantiphyse.packages.core.simulation
    - quantiphyse.packages.core.smoothing
    - quantiphyse.processes
    - quantiphyse.resources
    - quantiphyse.test
    - quantiphyse.utils
  commands:
    - quantiphyse --help

about:
  home: https://quantiphyse.readthedocs.io/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Quantiphyse is a data viewer and analysis platform for volumetric medical imaging data
  doc_url: https://quantiphyse.org
  dev_url: https://github.com/physimals/quantiphyse

extra:
  recipe-maintainers:
    - mcraig-ibme
